name: CI
on:
  workflow_dispatch:
    inputs:
      Username:
        description: Who is triggering this workflow - TELL ME YOUR NAME ???
        type: string

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: my name step
        run: echo My name is ${{ github.event.inputs.username }}


